### ISSUE TITLE
Peer-to-peer Code Review Feb 23

### ISSUE THREAD

**Issue by nxn404-n** [johnie261/to-do-list#3]
### You code was pretty good, but there is some few suggestions:

- In line 65 & 75 in your crud.js, can you please remove the inline comments.
- Please add a live link in your README.md file
- I think if you use class instead of individual functions in crud.js it would make your code more readable.

**Comment by johnie261** [comment]
Thank you very much @nxn404-n for the suggestions, I will consider the suggestions and apply them
